import { useEffect, useState } from 'react';
import { Compass, RotateCcw, RotateCw } from 'lucide-react';
import Modal from './Modal';

const cleanAngle=(v)=>((Number(v||0)%360)+360)%360;
const rotate=(value,delta)=>cleanAngle(Number(value||0)+delta);
function Actions({busy,onClose,label='Save & publish'}){return <div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={busy}>{busy?'Saving…':label}</button></div>}
function RotationButtons({value,onChange}){const angle=cleanAngle(value);return <div className="rotation-button-panel"><div className="orientation-dial compact-dial"><div className="orientation-arrow" style={{transform:`rotate(${angle}deg)`}}><span/></div><b>N</b></div><div className="rotation-button-copy"><span>Coverage rotation</span><strong>{angle.toFixed(0)}°</strong><small>Use the buttons to rotate the sensor proximity square. No angle typing needed.</small><div className="rotation-buttons"><button type="button" onClick={()=>onChange(rotate(angle,-15))}><RotateCcw size={15}/>Rotate left</button><button type="button" onClick={()=>onChange(rotate(angle,15))}><RotateCw size={15}/>Rotate right</button><button type="button" onClick={()=>onChange(0)}><Compass size={15}/>North</button></div></div></div>}

export function SensorEditorModal({sensor,onClose,onSave,busy=false}){
  const [f,setF]=useState(sensor||{});useEffect(()=>setF(sensor||{}),[sensor?.id]);const set=(k,v)=>setF(x=>({...x,[k]:v}));if(!sensor)return null;
  return <Modal title={`Edit ${sensor.sensor_code}`} subtitle="Update the published sensor values and rotate its coverage using buttons." onClose={onClose} wide className="fixed-editor-modal"><form className="modal-form" onSubmit={e=>{e.preventDefault();onSave({...sensor,...f,orientation_deg:cleanAngle(f.orientation_deg)})}}><div className="editor-two-column"><section><h4>Station & placement</h4><div className="form-grid two"><label>Sensor name<input value={f.sensor_code||''} onChange={e=>set('sensor_code',e.target.value)}/></label><label>Status<select value={f.status||'Online'} onChange={e=>set('status',e.target.value)}><option>Online</option><option>Offline</option><option>Maintenance</option></select></label><label>Coverage square (meters)<input type="number" min="1" value={f.coverage_m??50} onChange={e=>set('coverage_m',e.target.value)}/></label><label>Latitude<input type="number" step="0.000001" value={f.latitude??''} onChange={e=>set('latitude',e.target.value)}/></label><label>Longitude<input type="number" step="0.000001" value={f.longitude??''} onChange={e=>set('longitude',e.target.value)}/></label></div><RotationButtons value={f.orientation_deg} onChange={v=>set('orientation_deg',v)}/></section><section><h4>Published soil readings</h4><div className="form-grid two"><label>Nitrogen (mg/kg)<input type="number" step="0.01" value={f.nitrogen??''} onChange={e=>set('nitrogen',e.target.value)}/></label><label>Phosphorus (mg/kg)<input type="number" step="0.01" value={f.phosphorus??''} onChange={e=>set('phosphorus',e.target.value)}/></label><label>Potassium (mg/kg)<input type="number" step="0.01" value={f.potassium??''} onChange={e=>set('potassium',e.target.value)}/></label><label>Organic material (%)<input type="number" step="0.01" value={f.organic_matter??''} onChange={e=>set('organic_matter',e.target.value)}/></label><label>pH<input type="number" step="0.01" value={f.ph??''} onChange={e=>set('ph',e.target.value)}/></label><label>Moisture (%)<input type="number" step="0.01" value={f.moisture??''} onChange={e=>set('moisture',e.target.value)}/></label></div></section></div><Actions busy={busy} onClose={onClose}/></form></Modal>;
}

export function PlotEditorModal({plot,onClose,onSave,busy=false}){const [f,setF]=useState(plot||{});useEffect(()=>setF(plot||{}),[plot?.id]);const set=(k,v)=>setF(x=>({...x,[k]:v}));if(!plot)return null;return <Modal title={`Edit ${plot.plot_code}`} subtitle="Update the soil-analysis values published for this plot." onClose={onClose} wide className="fixed-editor-modal"><form className="modal-form" onSubmit={e=>{e.preventDefault();onSave({...plot,...f})}}><div className="form-grid two"><label>Plot name<input value={f.plot_code||''} onChange={e=>set('plot_code',e.target.value)}/></label><label>Classification<select value={f.classification||'Pending'} onChange={e=>set('classification',e.target.value)}><option>Pending</option><option>Good</option><option>Monitor</option><option>Poor</option><option>Critical</option></select></label><label>Nitrogen<input type="number" step="0.01" value={f.nitrogen??''} onChange={e=>set('nitrogen',e.target.value)}/></label><label>Phosphorus<input type="number" step="0.01" value={f.phosphorus??''} onChange={e=>set('phosphorus',e.target.value)}/></label><label>Potassium<input type="number" step="0.01" value={f.potassium??''} onChange={e=>set('potassium',e.target.value)}/></label><label>Organic material (%)<input type="number" step="0.01" value={f.organic_matter??''} onChange={e=>set('organic_matter',e.target.value)}/></label><label>pH<input type="number" step="0.01" value={f.ph??''} onChange={e=>set('ph',e.target.value)}/></label><label className="full">Notes<textarea rows="3" value={f.notes||''} onChange={e=>set('notes',e.target.value)}/></label></div><Actions busy={busy} onClose={onClose}/></form></Modal>}

export function DroneEditorModal({drone,onClose,onSave,busy=false}){const [f,setF]=useState(drone||{});useEffect(()=>setF(drone||{}),[drone?.id]);const set=(k,v)=>setF(x=>({...x,[k]:v}));if(!drone)return null;return <Modal title={`Edit ${drone.name}`} subtitle="Update the drone-mapping observations published to this farmer." onClose={onClose} wide className="fixed-editor-modal"><form className="modal-form" onSubmit={e=>{e.preventDefault();onSave({...drone,...f})}}><div className="form-grid two"><label>Mapping name<input value={f.name||''} onChange={e=>set('name',e.target.value)}/></label><label>Classification<select value={f.classification||'Unclassified'} onChange={e=>set('classification',e.target.value)}><option>Unclassified</option><option>Good</option><option>Monitor</option><option>Poor</option><option>Critical</option></select></label><label>Status<select value={f.status||'Mapped'} onChange={e=>set('status',e.target.value)}><option>Mapped</option><option>Processing</option><option>Archived</option></select></label><label>Nitrogen<input type="number" step="0.01" value={f.nitrogen??''} onChange={e=>set('nitrogen',e.target.value)}/></label><label>Phosphorus<input type="number" step="0.01" value={f.phosphorus??''} onChange={e=>set('phosphorus',e.target.value)}/></label><label>Potassium<input type="number" step="0.01" value={f.potassium??''} onChange={e=>set('potassium',e.target.value)}/></label><label>Organic material (%)<input type="number" step="0.01" value={f.organic_matter??''} onChange={e=>set('organic_matter',e.target.value)}/></label><label>pH<input type="number" step="0.01" value={f.ph??''} onChange={e=>set('ph',e.target.value)}/></label><label>Moisture (%)<input type="number" step="0.01" value={f.moisture??''} onChange={e=>set('moisture',e.target.value)}/></label><label className="full">Image / orthomosaic URL<input value={f.image_url||''} onChange={e=>set('image_url',e.target.value)}/></label><label className="full">Notes<textarea rows="3" value={f.notes||''} onChange={e=>set('notes',e.target.value)}/></label></div><Actions busy={busy} onClose={onClose}/></form></Modal>}

export { RotationButtons, cleanAngle };
